[functions.monday-oauth-callback]
verify_jwt = false

[functions.monday-token-refresh]  
verify_jwt = false

[functions.get-monday-client-id]
verify_jwt = false

[functions.monday-session-verify]
verify_jwt = false

[functions.google-oauth-exchange]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false

[functions.check-google-connection]
verify_jwt = false

[functions.list-google-spreadsheets]
verify_jwt = false

[functions.list-google-sheets]
verify_jwt = false

[functions.gs-list-spreadsheets]
verify_jwt = false

[functions.gs-list-sheets]
verify_jwt = false

[functions.disconnect-google-sheets]
verify_jwt = false