// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynjkqxwwsoyklmualghy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluamtxeHd3c295a2xtdWFsZ2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTQzMzgsImV4cCI6MjA3NjE5MDMzOH0.Rl9TYlQSGKPgPLmUR2HcWI3KmvOIQgN3QdU9wZUkRLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});